apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: k3d-runner-autoscaler
  namespace: arc-runners
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: k3d-github-runner
  minReplicas: 1 # Set minReplicas to 1 if you want 1 warm runner standing by
  maxReplicas: 5
  scaleUpTriggers:
    - githubEvent: {}
      duration: "5m" # Holds capacity longer to stop rapid scale-down