apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k3d-github-runner
  namespace: arc-runners
spec:
  template:
    spec:
      repository: omajimenal/k3d-gitops-infrastructure
      ephemeral: true